language: node_js
node_js:
  - "6"
cache:
  directories:
  - node_modules
script:
  - yarn run test-coverage
  - yarn run coverage
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
